spring:
  application:
    name: music
  r2dbc:
    url: localhost
    username: root
    password: root
logging:
  level:
    com:
      example:
        music: debug
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus" # prometheus는 추후 시각화에 유용합니다
  endpoint:
    metrics:
      access: READ_ONLY
resource:
  json:
    path: path