spring:
  application:
    name: music
  r2dbc:
    url: localhost
    username: root
    password: root
logging:
  level:
    com:
      example:
        music: debug
    org:
      springframework:
        r2dbc: debug
resource:
  json:
    path: path